import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TodoList",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-[linear-gradient(to_bottom_left,rgb(8,8,11),rgb(28,28,39),rgb(8,8,11))]
`}
      >
        <Toaster position="top-right" richColors closeButton />
        {children}
      </body>
    </html>
  );
}
